### ISSUE TITLE
about the paper

### ISSUE THREAD

**Issue by suetme** [syau-miao/QSSP#1]
Thank you for your wonderful work!
I want to know which journal you published this paper in.

**Comment by syau-miao** [comment]
Thank you for your attention to our work. We haven't submitted this paper yet. It is estimated that the paper will be submitted next week. Maybe I will upload the paper to arxiv these days

**Comment by suetme** [comment]
Well, I hope your paper will be published soon.

**Comment by syau-miao** [comment]
Thank you
